app = 'elearnio-articles-api'
primary_region = 'ams'

[build]

[env]
  BINDING = '::'
  RAILS_LOG_LEVEL = 'info'
  RAILS_MAX_THREADS = '3'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = 'sqlite_data'
  destination = '/rails/storage'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[checks]
  [checks.health]
    type = 'http'
    port = 3000
    path = '/up'
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
